// <auto-generated />
using System;
using LlmShadow.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LlmShadow.DataLayer.Migrations
{
    [DbContext(typeof(ShadowDbContext))]
    partial class ShadowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LlmShadow.DataLayer.Models.RequestRecord", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("CandidateModel")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("EvaluatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<bool?>("IsMatch")
                    .HasColumnType("boolean");

                b.Property<double?>("MatchPercentage")
                    .HasColumnType("double precision");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTime>("ModifiedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("RequestPayloadJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("RequestId")
                    .HasColumnType("uuid");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id");
                b.HasIndex("RequestId").IsUnique();
                b.HasIndex("Status", "CreatedAtUtc");
                b.ToTable("Requests");
            });

            modelBuilder.Entity("LlmShadow.DataLayer.Models.PrimaryLlmResponse", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                b.Property<string>("ErrorMessage").HasColumnType("text");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<bool>("IsError").HasColumnType("boolean");
                b.Property<long>("LatencyMs").HasColumnType("bigint");
                b.Property<DateTime>("ModifiedAtUtc").HasColumnType("timestamp with time zone");
                b.Property<Guid>("RequestId").HasColumnType("uuid");
                b.Property<string>("ResponseText").HasColumnType("text");

                b.HasKey("Id");
                b.HasIndex("RequestId");
                b.ToTable("PrimaryLlmResponses");
            });

            modelBuilder.Entity("LlmShadow.DataLayer.Models.SecondaryLlmResponse", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                b.Property<string>("ErrorMessage").HasColumnType("text");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<bool>("IsError").HasColumnType("boolean");
                b.Property<long>("LatencyMs").HasColumnType("bigint");
                b.Property<DateTime>("ModifiedAtUtc").HasColumnType("timestamp with time zone");
                b.Property<Guid>("RequestId").HasColumnType("uuid");
                b.Property<string>("ResponseText").HasColumnType("text");

                b.HasKey("Id");
                b.HasIndex("RequestId");
                b.ToTable("SecondaryLlmResponses");
            });

            modelBuilder.Entity("LlmShadow.DataLayer.Models.PrimaryLlmResponse", b =>
            {
                b.HasOne("LlmShadow.DataLayer.Models.RequestRecord", "Request")
                    .WithOne("PrimaryResponse")
                    .HasForeignKey("LlmShadow.DataLayer.Models.PrimaryLlmResponse", "RequestId")
                    .HasPrincipalKey("LlmShadow.DataLayer.Models.RequestRecord", "RequestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Request");
            });

            modelBuilder.Entity("LlmShadow.DataLayer.Models.SecondaryLlmResponse", b =>
            {
                b.HasOne("LlmShadow.DataLayer.Models.RequestRecord", "Request")
                    .WithOne("SecondaryResponse")
                    .HasForeignKey("LlmShadow.DataLayer.Models.SecondaryLlmResponse", "RequestId")
                    .HasPrincipalKey("LlmShadow.DataLayer.Models.RequestRecord", "RequestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Request");
            });

            modelBuilder.Entity("LlmShadow.DataLayer.Models.RequestRecord", b =>
            {
                b.Navigation("PrimaryResponse");
                b.Navigation("SecondaryResponse");
            });
#pragma warning restore 612, 618
        }
    }
}
